### ISSUE TITLE
Make email once submitted to send a email to me that someone submitted their email.

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/bootstrap#1]
When the email is submitted, send me a email on kendall@kendalldoescoding.gq that someone has submitted their email, this isn't that important, but a nice touch!

Can be done using a tool.

![image](https://user-images.githubusercontent.com/84712013/182906250-c13f53e1-1712-439f-bc1d-8130845e2b0e.png)

**Comment by KendallDoesCoding** [comment]
@vikasgangia05 any idea how this can be done?

**Comment by KendallDoesCoding** [comment]
@vikasganiga05 any idea how this can be done?

**Comment by vikasganiga05** [comment]
> @vikasganiga05 any idea how this can be done?

I don't know right now. I will let you know once I will find the solution. Which hosting platform you're using to host this site?

**Comment by KendallDoesCoding** [comment]
> > @vikasganiga05 any idea how this can be done?
> 
> I don't know right now. I will let you know once I will find the solution. Which hosting platform you're using to host this site?

Ok. I'm using Netlify.. Thanks!

**Comment by danielafriheart** [comment]
you need to integrate a third-party mailer to do that for example you can try SmtpJS through elasticemail.com

**Comment by KendallDoesCoding** [comment]
Thanks, will have a look.

**Comment by michagodfrey** [comment]
I have implemented this feature before on my project showcase with EmailJS. 

If you like, I can try to add that feature to this site so you get an email when someone submits their email.

**Comment by KendallDoesCoding** [comment]
> I have implemented this feature before on my project showcase with EmailJS.
> 
> If you like, I can try to add that feature to this site so you get an email when someone submits their email.

Sure! I actually have been using formsubmit these days, this is my old project, so if you can implement EmailJS or Formsubmit, it'd be great.

**Comment by michagodfrey** [comment]
Ok, I'll get on it. Maybe Formsubmit is simpler and better for this project, I'll look into that go with what works best.

**Comment by KendallDoesCoding** [comment]
Ok. thanks a ton!

**Comment by KendallDoesCoding** [comment]
Hi, I got a email to active formsubmit, was that you?

Put your email for now, do the validation, see if it works, then change the
email and make the PR.

**Comment by KendallDoesCoding** [comment]
done in #2

**Comment by michagodfrey** [comment]
Yes, it was me. Sorry about that. I already checked with my email and it was working. I added yours in before making the pull request but accidentally did another test.

**Comment by KendallDoesCoding** [comment]
Oh ok. No worries
